export const categories = [
  { value: 0, label: "All" },
  { value: 1, label: "React js" },
  { value: 2, label: "Angular js" },
  { value: 3, label: "React Native" },
  { value: 4, label: "use of API" },
  { value: 5, label: "Redux" },
  { value: 7, label: "Ballcat" },
  { value: 8, label: "Clones" },
  { value: 9, label: "Tankster.io" },
  { value: 10, label: "Youtube clone" },
  { value: 11, label: "#programming" },
  { value: 12, label: "Online games" },
  { value: 13, label: "Redux Thunk" },
  { value: 14, label: "#coding" },
  { value: 15, label: "Discord" },
  { value: 16, label: "#gaming" },
  { value: 17, label: "#tastyrecipes" },
  { value: 18, label: "#recipes" },
  { value: 19, label: "#trending" },
  { value: 20, label: "#meme" },
  { value: 21, label: "#techtips" },
  { value: 22, label: "#technews" },
  { value: 23, label: "#tech" },
  { value: 24, label: "#youtuber" },
  { value: 25, label: "#youtube" },
  { value: 26, label: "Github" },
  { value: 28, label: "Stackoverflow" },
  { value: 29, label: "Cats" },
  { value: 27, label: "#india" },
  { value: 30, label: "Bruh" },
];
